### ISSUE TITLE
Custom Adjust not working .

### ISSUE THREAD

**Issue by ashokavarthanan** [rohansohonee/equalizer#2]
Custom Adjust not working .
When using preset its working ,but adjust slider not working or not changing effects.

**Comment by rohansohonee** [comment]
@ashokavarthanan 
Thank you for sharing this feedback. I will look into this issue and get back to you with the solution.
I would appreciate if you can share more detailed information in the future.

**Comment by rohansohonee** [comment]
@ashokavarthanan 
Please test the latest commit and let me know if this solves your issue.

**Comment by ashokavarthanan** [comment]
Wow. That's Great. Now working fine.
One Question.
Eq Hz:  60, 230, 91 and 3600 Hz are SET -15
then 14000 Hz  increase from -15 to +15 
why other Hz are Affecting? like 230Hz more Affects.
this is not Bug. but just asking for clarification. 
Thanks.

**Comment by rohansohonee** [comment]
The human hearing has a frequency range of 20 to 20,000 Hz. So I guess the 14,000 Hz effect is subtle.
Anyhow I am closing this issue as it is resolved. Will publish this change soon on pub.dev

**Comment by Mood-al** [comment]
> The human hearing has a frequency range of 20 to 20,000 Hz. So I guess the 14,000 Hz effect is subtle.
> Anyhow I am closing this issue as it is resolved. Will publish this change soon on pub.dev

hey man i want to change the fixed values of the equalizer to these values 
250 , 500 , 1000 , 2000 , 4000 , 8000
so im wondering if i can do that 
im using the example in the repo
i tried to add some values to this Equalizer.getCenterBandFreqs();
but it turned out that i cant do that 

![image](https://user-images.githubusercontent.com/63562308/103808074-daa90000-5070-11eb-8572-7162c0236dab.png)
