### ISSUE TITLE
Attaching an Equalizer to the global audio output mix by use of session 0 is deprecated : Equalizer.init(1);

### ISSUE THREAD

**Issue by ECOS-dev** [rohansohonee/equalizer#5]
**Describe the bug** :
void initState() {
    super.initState();
    **Equalizer.init(1);**

and 

return Container(
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: snapshot.data.map<**Widget**>((freq) => _buildSliderBand(freq, bandId++)).toList(),
                      ),

(see https://www.javaer101.com/en/article/7007200.html)

**Comment by rohansohonee** [comment]
@ECOS-dev 

In the example I have provided a 0 value for demonstration purposes so that the custom equalizer can be setup. In a real app you must provide a valid session id that will be provided to you by your audio player.

Reference to a flutter plugin that provides you with a audioSessionId: https://pub.dev/packages/just_audio#platform-specific-configuration
